[package]
name = "reddit_reposts"
version = "0.1.0"
authors = ["mfehr <mathieu.fehr@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.88", features = ["derive"] }
serde_json = "1.0.38"
regex = "1.1.0"
